name: Local
values:
  - key: baseUrl
    value: 'http://localhost:3200'
    enabled: true
  - key: plaidClientId
    value: ''
    enabled: true
  - key: plaidSecret
    value: ''
    enabled: true
  - key: plaidPublicToken
    value: ''
    enabled: true
  - key: betterAuthEmail
    value: ''
    enabled: true
  - key: betterAuthPassword
    value: ''
    enabled: true
  - key: betterAuthFullName
    value: ''
    enabled: true
  - key: betterAuthFirstName
    value: ''
    enabled: true
  - key: betterAuthMiddleName
    value: ''
    enabled: true
  - key: betterAuthLastName
    value: ''
    enabled: true
